spring.application.name=ulapedidos
server.port = 8086

# Oracle
spring.datasource.url = jdbc:oracle:thin:@localhost:1522:xe
spring.datasource.username = ULAPEDIDOS
spring.datasource.password = ulapedidos
spring.detasourcce.driver-class-name = oracle.jdbc.OracleDriver

# JPA
spring.jpa.hibernate.ddl-auto = none
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true;

# Oracle Dialect
spring.jpa.database-platform = org.hibernate.dialect.OracleDialect

spring.sql.init.mode = always