-- ====================
-- Tabla Auditoria: PAIS
-- ====================

alter session set current_schema = SECURITY;

-- ====================
-- Funcion de obtener IP
-- ====================

CREATE  OR REPLACE FUNCTION FN_GET_IP
    RETURN VARCHAR2
    IS
BEGIN
    -- Intento de obtener IP del host que hace conexión
    RETURN NVL(SYS_CONTEXT('USERENV', 'IP_ADDRESS'), SYS_CONTEXT('USERENV', 'HOST'));
EXCEPTION
    WHEN OTHERS THEN
        RETURN 'LOCALHOST';
END FN_GET_IP;

-- ====================
-- Funcion de obtener FECHA Y HORA
-- ====================
CREATE OR REPLACE FUNCTION FN_GET_FECHA
    RETURN TIMESTAMP
    IS
BEGIN
    RETURN SYSTIMESTAMP;
EXCEPTION
    WHEN OTHERS THEN
        RETURN NULL;
END FN_GET_FECHA;
/




--- *********************************************************************** Tabla BIT: PAIS
BEGIN
    EXECUTE IMMEDIATE  'DROP TABLE BIT_PAIS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

---- Creando Tabla BIT
CREATE TABLE BIT_PAIS(
     ID_PAIS_BIT VARCHAR2(36) NOT NULL,
     UUID_PAIS VARCHAR2(36) NOT NULL,
     CODIGO VARCHAR(5),
     DESCRIPTION VARCHAR(255),
     ESTADO NUMBER(2) NOT NULL,
     FECHA_CREACION TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
     CREADO_POR VARCHAR(36) NOT NULL,
     FECHA_ACTUALIZACION TIMESTAMP,
     ACTUALIZADO_POR VARCHAR2(36),
     NOTAS VARCHAR2(100),
     CONSTRAINT pk_id_pais_bit_pais_bit PRIMARY KEY (ID_PAIS_BIT)
);

COMMENT ON TABLE BIT_PAIS IS 'Tabla que de Bitacora que contiene la información del PAIS';
COMMENT ON COLUMN BIT_PAIS.ID_PAIS_BIT IS 'ID_BIT de tabla PAIS';
COMMENT ON COLUMN BIT_PAIS.UUID_PAIS IS 'Identificador único UUID';
COMMENT ON COLUMN BIT_PAIS.CODIGO IS 'Código del país';
COMMENT ON COLUMN BIT_PAIS.DESCRIPTION IS 'Nombre o descripción del país';
COMMENT ON COLUMN BIT_PAIS.ESTADO IS '0 = Inactivo | 99 = Activo';
COMMENT ON COLUMN BIT_PAIS.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN BIT_PAIS.CREADO_POR IS 'Usuario creador';
COMMENT ON COLUMN BIT_PAIS.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN BIT_PAIS.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN BIT_PAIS.NOTAS IS 'Observaciones adicionales';

COMMIT;

-- ====================
-- Trigger Auditoria PAIS
-- ====================

CREATE OR REPLACE TRIGGER TRG_PAIS_AUD
    AFTER INSERT OR UPDATE ON CAT_PAIS
    FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

        -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_CREACION;

        -- Detectar borrado logico
        IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'ACTIVATE';
        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'DEACTIVATE';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;
    END IF;

    INSERT INTO BIT_PAIS (
        ID_PAIS_BIT,
        UUID_PAIS,
        CODIGO,
        DESCRIPTION,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS
    )
    VALUES (
               SYS_GUID(),
               :NEW.UUID_PAIS,
               :NEW.CODIGO,
               :NEW.DESCRIPTION,
               :NEW.ESTADO,
               V_FECHA_CREACION,
               :NEW.CREADO_POR,
               V_FECHA_MODIFICACION,
               FN_GET_IP,
               V_ACCION
           );
END;
/

--- INSERT INTO CAT_PAIS (UUID_PAIS, CODIGO, DESCRIPTION, ESTADO,  CREADO_POR, FECHA_ACTUALIZACION, ACTUALIZADO_POR, NOTAS)
--- VALUES ('EXAMPLE1-62c4-4b6a-b432-f614a8624d36', 'EXJ', 'EJEMPLO1', 0,  '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e', null, null, null);
--- COMMIT;

SELECT * FROM BIT_PAIS;





--- *********************************************************************** Tabla BIT: ESTADO
BEGIN
    EXECUTE IMMEDIATE  'DROP TABLE BIT_ESTADO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

---- Creando Tabla BIT
CREATE TABLE BIT_ESTADO(
         ID_ESTADO_BIT VARCHAR2(36) NOT NULL,
         UUID_ESTADO VARCHAR2(36) NOT NULL,
         UUID_PAIS VARCHAR2(36) DEFAULT '34a03599-6d56-4c0c-aff0-f887ca20ea93',
         DESCRIPTION VARCHAR2(35) NOT NULL,
         ESTADO NUMBER(2) NOT NULL,
         FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
         CREADO_POR VARCHAR2(36) NOT NULL,
         FECHA_ACTUALIZACION TIMESTAMP,
         ACTUALIZADO_POR VARCHAR2(36),
         NOTAS VARCHAR2(100),
         CONSTRAINT pk_id_estado_bit_estado_bit PRIMARY KEY (ID_ESTADO_BIT)
);

COMMENT ON TABLE BIT_ESTADO IS 'Tabla que de Bitacora que contiene la información del ESTADO';
COMMENT ON COLUMN BIT_ESTADO.ID_ESTADO_BIT IS 'ID_ESTADO_BIT de tabla ESTADO';
COMMENT ON COLUMN BIT_ESTADO.UUID_ESTADO IS 'Identificador único UUID del estado';
COMMENT ON COLUMN BIT_ESTADO.UUID_PAIS IS 'Referencia al país';
COMMENT ON COLUMN BIT_ESTADO.DESCRIPTION IS 'Nombre del estado';
COMMENT ON COLUMN BIT_ESTADO.ESTADO IS '0 = Inactivo | 99 = Activo';
COMMENT ON COLUMN BIT_ESTADO.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN BIT_ESTADO.CREADO_POR IS 'Usuario creador';
COMMENT ON COLUMN BIT_ESTADO.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN BIT_ESTADO.ACTUALIZADO_POR IS 'Usuario actualizador';
COMMENT ON COLUMN BIT_ESTADO.NOTAS IS 'Observaciones';

COMMIT;

-- ====================
-- Trigger Auditoria PAIS
-- ====================

CREATE OR REPLACE TRIGGER TRG_ESTADO_AUD
    AFTER INSERT OR UPDATE ON CAT_ESTADO
    FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

        -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_CREACION;

        -- Detectar borrado logico
        IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'ACTIVATE';
        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'DEACTIVATE';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;
    END IF;

    INSERT INTO BIT_ESTADO (
        ID_ESTADO_BIT,
        UUID_ESTADO,
        UUID_PAIS,
        DESCRIPTION,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS
    )
    VALUES (
               SYS_GUID(),
               :NEW.UUID_ESTADO,
               :NEW.UUID_PAIS,
               :NEW.DESCRIPTION,
               :NEW.ESTADO,
               V_FECHA_CREACION,
               :NEW.CREADO_POR,
               V_FECHA_MODIFICACION,
               FN_GET_IP,
               V_ACCION
           );
END;
/

-- INSERT INTO CAT_ESTADO (UUID_ESTADO, DESCRIPTION, ESTADO,  CREADO_POR, FECHA_ACTUALIZACION, ACTUALIZADO_POR, NOTAS)
-- VALUES ('EXAMPLE2-62c4-4b6a-b432-f614a8624d36', 'EJEMPLO_ESTADO2', 0,  '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e', null, null, null);
-- COMMIT;

SELECT * FROM BIT_ESTADO;





--- *********************************************************************** Tabla BIT: CIUDAD
BEGIN
    EXECUTE IMMEDIATE  'DROP TABLE BIT_CIUDAD CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

---- Creando Tabla BIT
CREATE TABLE BIT_CIUDAD(
       ID_CIUDAD_BIT VARCHAR2(36) NOT NULL,
       UUID_CIUDAD VARCHAR2(36) NOT NULL,
       UUID_ESTADO VARCHAR2(36) NOT NULL,
       DESCRIPTION VARCHAR2(50) NOT NULL,
       ESTADO NUMBER(2) NOT NULL,
       FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
       CREADO_POR VARCHAR2(36) NOT NULL,
       FECHA_ACTUALIZACION TIMESTAMP,
       ACTUALIZADO_POR VARCHAR2(36),
       NOTAS VARCHAR2(100),
       CONSTRAINT pk_id_ciudad_bit_ciudad_bit PRIMARY KEY (ID_CIUDAD_BIT)
);

COMMENT ON TABLE BIT_CIUDAD IS 'Tabla que de Bitacora que contiene la información de la CIUDAD';
COMMENT ON COLUMN BIT_CIUDAD.ID_CIUDAD_BIT IS 'ID_CIUDAD_BIT de tabla CIUDAD';
COMMENT ON COLUMN BIT_CIUDAD.UUID_CIUDAD IS 'Identificador único UUID de la ciudad';
COMMENT ON COLUMN BIT_CIUDAD.UUID_ESTADO IS 'Referencia al estado';
COMMENT ON COLUMN BIT_CIUDAD.DESCRIPTION IS 'Nombre de la ciudad';
COMMENT ON COLUMN BIT_CIUDAD.ESTADO IS '0 = Inactivo, 99 = Activo';
COMMENT ON COLUMN BIT_CIUDAD.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN BIT_CIUDAD.CREADO_POR IS 'Usuario creador';
COMMENT ON COLUMN BIT_CIUDAD.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN BIT_CIUDAD.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN BIT_CIUDAD.NOTAS IS 'Observaciones adicionales';

COMMIT;

-- ====================
-- Trigger Auditoria CIUDAD
-- ====================

CREATE OR REPLACE TRIGGER TRG_CIUDAD_AUD
    AFTER INSERT OR UPDATE ON CAT_CIUDAD
    FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

        -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_CREACION;

        -- Detectar borrado logico
        IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'ACTIVATE';
        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'DEACTIVATE';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;
    END IF;

    INSERT INTO BIT_CIUDAD (
        ID_CIUDAD_BIT,
        UUID_CIUDAD,
        UUID_ESTADO,
        DESCRIPTION,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS
    )
    VALUES (
               SYS_GUID(),
               :NEW.UUID_CIUDAD,
               :NEW.UUID_ESTADO,
               :NEW.DESCRIPTION,
               :NEW.ESTADO,
               V_FECHA_CREACION,
               :NEW.CREADO_POR,
               V_FECHA_MODIFICACION,
               FN_GET_IP,
               V_ACCION
           );
END;
/

-- INSERT INTO CAT_CIUDAD (UUID_CIUDAD, UUID_ESTADO, DESCRIPTION, ESTADO,  CREADO_POR, FECHA_ACTUALIZACION, ACTUALIZADO_POR, NOTAS)
-- VALUES ('EXAMPLE1-62c4-4b6a-b432-f614a8624d36', '79b7598b-fe1e-4921-87ed-70af359a41ab', 'EJEMPLO CIUDAD', 0,  '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e', null, null, null);
-- COMMIT;

SELECT * FROM BIT_CIUDAD;





--- *********************************************************************** Tabla BIT: FACTURA
BEGIN
    EXECUTE IMMEDIATE  'DROP TABLE BIT_ESTADO_FACTURA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

---- Creando Tabla BIT
CREATE TABLE BIT_ESTADO_FACTURA(
       ID_ESTADO_FACTURA_BIT VARCHAR2(36) NOT NULL,
       ID_ESTADO_FACTURA VARCHAR2(15) NOT NULL,
       NOMBRE VARCHAR2(50) NOT NULL,
       DESCRIPTION VARCHAR2(100),
       ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
       FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
       CREADO_POR VARCHAR2(36) NOT NULL,
       FECHA_ACTUALIZACION TIMESTAMP,
       ACTUALIZADO_POR VARCHAR2(36),
       NOTAS VARCHAR2(100),
       CONSTRAINT pk_id_state_facture_bit_state_facture_bit PRIMARY KEY (ID_ESTADO_FACTURA_BIT)
);

COMMENT ON TABLE BIT_ESTADO_FACTURA IS 'Tabla que de Bitacora que contiene la información del ESTADO DE LA FACTURA';
COMMENT ON COLUMN BIT_ESTADO_FACTURA.ID_ESTADO_FACTURA_BIT IS 'ID_ESTADO_FACTURA_BIT de tabla FACTURAS';
COMMENT ON COLUMN BIT_ESTADO_FACTURA.ID_ESTADO_FACTURA IS 'Clave del estado de la factura';
COMMENT ON COLUMN BIT_ESTADO_FACTURA.NOMBRE IS 'Nombre del estado de la factura';
COMMENT ON COLUMN BIT_ESTADO_FACTURA.DESCRIPTION IS 'Descripción del estado de la factura';
COMMENT ON COLUMN BIT_ESTADO_FACTURA.ESTADO IS '0 = Activo | 99 = Inactivo';
COMMENT ON COLUMN BIT_ESTADO_FACTURA.FECHA_CREACION is 'Fecha de creación';
COMMENT ON COLUMN BIT_ESTADO_FACTURA.CREADO_POR is 'Usuario creador';
COMMENT ON COLUMN BIT_ESTADO_FACTURA.FECHA_ACTUALIZACION is 'Fecha de actualización';
COMMENT ON COLUMN BIT_ESTADO_FACTURA.ACTUALIZADO_POR is 'Usuario que actualizó';

COMMIT;

-- ====================
-- Trigger Auditoria FACTURAS
-- ====================

CREATE OR REPLACE TRIGGER TRG_FACTURA_AUD
    AFTER INSERT OR UPDATE ON CAT_ESTADO_FACTURA
    FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

        -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_CREACION;

        -- Detectar borrado logico
        IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'ACTIVATE';
        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'DEACTIVATE';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;
    END IF;

    INSERT INTO BIT_ESTADO_FACTURA (
        ID_ESTADO_FACTURA_BIT,
        ID_ESTADO_FACTURA,
        NOMBRE,
        DESCRIPTION,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS
    )
    VALUES (
               SYS_GUID(),
               :NEW.ID_ESTADO_FACTURA,
               :NEW.NOMBRE,
               :NEW.DESCRIPTION,
               :NEW.ESTADO,
               V_FECHA_CREACION,
               :NEW.CREADO_POR,
               V_FECHA_MODIFICACION,
               FN_GET_IP,
               V_ACCION
           );
END;
/

--INSERT INTO CAT_ESTADO_FACTURA(NOMBRE, DESCRIPTION, CREADO_POR)
--VALUES ('PAGADA-EX', 'Factura Pagada EJEMPLO', '57e8cc9c-9dB3-4e76-99c1-d6de3d7a984e');
-- COMMIT;


SELECT * FROM BIT_ESTADO_FACTURA;





--- *********************************************************************** Tabla BIT: PAGOS
BEGIN
    EXECUTE IMMEDIATE  'DROP TABLE BIT_ESTADO_PAGOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

---- Creando Tabla BIT
CREATE TABLE BIT_ESTADO_PAGOS(
       ID_ESTADO_PAGOS_BIT VARCHAR2(36) NOT NULL,
       ID_ESTADO_PAGO VARCHAR2(15) NOT NULL,
       NOMBRE VARCHAR2(50) NOT NULL,
       DESCRIPTION VARCHAR2(100),
       ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
       FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
       CREADO_POR VARCHAR2(36) NOT NULL,
       FECHA_ACTUALIZACION TIMESTAMP,
       ACTUALIZADO_POR VARCHAR2(36),
       NOTAS VARCHAR2(100),
       CONSTRAINT pk_id_state_payments_bit_state_payments_bit PRIMARY KEY (ID_ESTADO_PAGOS_BIT)
);

COMMENT ON TABLE BIT_ESTADO_PAGOS IS 'Tabla que de Bitacora que contiene la información de ESTADOS DE PAGOS';
COMMENT ON COLUMN BIT_ESTADO_PAGOS.ID_ESTADO_PAGOS_BIT IS 'ID_ESTADO_PAGOS_BIT de tabla PAGOS';
COMMENT ON COLUMN BIT_ESTADO_PAGOS.ID_ESTADO_PAGO IS 'Clave del estado de la pago';
COMMENT ON COLUMN BIT_ESTADO_PAGOS.NOMBRE IS 'Nombre del estado de la pago';
COMMENT ON COLUMN BIT_ESTADO_PAGOS.DESCRIPTION IS 'Descripción del estado de la pago';
COMMENT ON COLUMN BIT_ESTADO_PAGOS.ESTADO IS '0 = Activo | 99 = Inactivo';
COMMENT ON COLUMN BIT_ESTADO_PAGOS.FECHA_CREACION is 'Fecha de creación';
COMMENT ON COLUMN BIT_ESTADO_PAGOS.CREADO_POR is 'Usuario creador';
COMMENT ON COLUMN BIT_ESTADO_PAGOS.FECHA_ACTUALIZACION is 'Fecha de actualización';
COMMENT ON COLUMN BIT_ESTADO_PAGOS.ACTUALIZADO_POR is 'Usuario que actualizó';
COMMENT ON COLUMN BIT_ESTADO_PAGOS.NOTAS is 'Observaciones adicionales';

COMMIT;

-- ====================
-- Trigger Auditoria PAGOS
-- ====================

CREATE OR REPLACE TRIGGER TRG_PAGOS_AUD
    AFTER INSERT OR UPDATE ON CAT_ESTADO_PAGO
    FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

        -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_CREACION;

        -- Detectar borrado logico
        IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'ACTIVATE';
        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'DEACTIVATE';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;
    END IF;

    INSERT INTO BIT_ESTADO_PAGOS (
        ID_ESTADO_PAGOS_BIT,
        ID_ESTADO_PAGO,
        NOMBRE,
        DESCRIPTION,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS
    )
    VALUES (
               SYS_GUID(),
               :NEW.ID_ESTADO_PAGO,
               :NEW.NOMBRE,
               :NEW.DESCRIPTION,
               :NEW.ESTADO,
               V_FECHA_CREACION,
               :NEW.CREADO_POR,
               V_FECHA_MODIFICACION,
               FN_GET_IP,
               V_ACCION
           );
END;
/

--- INSERT INTO CAT_ESTADO_PAGO(NOMBRE, DESCRIPTION, CREADO_POR)
--- VALUES ('PROCESADO-EXMPL', 'pago PROCESADO CON EXITO EJEMPLO', '57e8cc9c-9dB3-4e76-99c1-d6de3d7a984e');
--- COMMIT;

SELECT * FROM BIT_ESTADO_PAGOS;





--- *********************************************************************** Tabla BIT: ROL
BEGIN
    EXECUTE IMMEDIATE  'DROP TABLE BIT_ROLES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

---- Creando Tabla BIT
CREATE TABLE BIT_ROLES(
       ID_ROLES_BIT VARCHAR2(36) NOT NULL,
       ID_ROL VARCHAR2(10) NOT NULL,
       NOMBRE_ROL VARCHAR2(50) NOT NULL,
       DESCRIPTION VARCHAR2(100),
       ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
       FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
       CREADO_POR VARCHAR2(36) NOT NULL,
       FECHA_ACTUALIZACION TIMESTAMP,
       ACTUALIZADO_POR VARCHAR2(36),
       NOTAS VARCHAR2(100),
       CONSTRAINT pk_id_roles_bit_roles_bit PRIMARY KEY (ID_ROLES_BIT)
);

COMMENT ON TABLE BIT_ROLES IS 'Tabla que de Bitacora que contiene la información de los ROLES';
COMMENT ON COLUMN BIT_ROLES.ID_ROLES_BIT IS 'ID_ROLES_BIT de tabla ROLES';
COMMENT ON COLUMN BIT_ROLES.ID_ROL IS 'Clave del ROL ejemplo RL-001';
COMMENT ON COLUMN BIT_ROLES.NOMBRE_ROL IS 'Nombre del ROL';
COMMENT ON COLUMN BIT_ROLES.DESCRIPTION IS 'Descripción del ROL';
COMMENT ON COLUMN BIT_ROLES.ESTADO IS '0 = Activo | 99 = Inactivo';
COMMENT ON COLUMN BIT_ROLES.FECHA_CREACION is 'Fecha de creación';
COMMENT ON COLUMN BIT_ROLES.CREADO_POR is 'Usuario creador';
COMMENT ON COLUMN BIT_ROLES.FECHA_ACTUALIZACION is 'Fecha de actualización';
COMMENT ON COLUMN BIT_ROLES.ACTUALIZADO_POR is 'Usuario que actualizó';
COMMENT ON COLUMN BIT_ROLES.NOTAS is 'Observaciones adicionales';

COMMIT;

-- ====================
-- Trigger Auditoria ROLES
-- ====================

CREATE OR REPLACE TRIGGER TRG_ROLES_AUD
    AFTER INSERT OR UPDATE ON CAT_ROL
    FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

        -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_CREACION;

        -- Detectar borrado logico
        IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'ACTIVATE';
        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'DEACTIVATE';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;
    END IF;

    INSERT INTO BIT_ROLES (
        ID_ROLES_BIT,
        ID_ROL,
        NOMBRE_ROL,
        DESCRIPTION,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS
    )
    VALUES (
               SYS_GUID(),
               :NEW.ID_ROL,
               :NEW.NOMBRE_ROL,
               :NEW.DESCRIPTION,
               :NEW.ESTADO,
               V_FECHA_CREACION,
               :NEW.CREADO_POR,
               V_FECHA_MODIFICACION,
               FN_GET_IP,
               V_ACCION
           );
END;
/

--- INSERT INTO CAT_ROL(NOMBRE_ROL, DESCRIPTION, CREADO_POR)
--- VALUES ('USER_TESTER', 'Usuario estandar PRUEBA', '57e8cc9c-9dB3-4e76-99c1-d6de3d7a984e');
--- COMMIT;

SELECT * FROM BIT_ROLES;





--- *********************************************************************** Tabla BIT: CAT MENSAJES
BEGIN
    EXECUTE IMMEDIATE  'DROP TABLE BIT_STATUS_MENSAJE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

---- Creando Tabla BIT
CREATE TABLE BIT_STATUS_MENSAJE(
       ID_STATUS_MENSAJE_BIT VARCHAR2(36) NOT NULL,
       ID_STATUS_MENSAJE VARCHAR2(15) NOT NULL,
       NOMBRE_STATUS VARCHAR2(40) NOT NULL,
       DESCRIPTION VARCHAR2(100),
       ESTADO NUMBER(2) DEFAULT 1 NOT NULL,
       FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
       CREADO_POR VARCHAR2(36) NOT NULL,
       FECHA_ACTUALIZACION TIMESTAMP,
       ACTUALIZADO_POR VARCHAR2(36),
       NOTAS VARCHAR2(100),
       CONSTRAINT pk_id_state_mensagge_bit_state_mensagge_bit PRIMARY KEY (ID_STATUS_MENSAJE_BIT)
);

COMMENT ON TABLE BIT_STATUS_MENSAJE IS 'Tabla que de Bitacora que contiene la información de los ESTADO_MENSAJES';
COMMENT ON COLUMN BIT_STATUS_MENSAJE.ID_STATUS_MENSAJE_BIT IS 'ID_STATUS_MENSAJE_BIT de tabla ESTADO_MENSAJES';
COMMENT ON COLUMN BIT_STATUS_MENSAJE.ID_STATUS_MENSAJE IS 'ID de estado';
COMMENT ON COLUMN BIT_STATUS_MENSAJE.NOMBRE_STATUS IS 'Estado del mensaje';
COMMENT ON COLUMN BIT_STATUS_MENSAJE.DESCRIPTION IS 'Descripción del estado';
COMMENT ON COLUMN BIT_STATUS_MENSAJE.ESTADO IS 'Estado del registro';
COMMENT ON COLUMN BIT_STATUS_MENSAJE.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN BIT_STATUS_MENSAJE.CREADO_POR IS 'Usuario Creador';
COMMENT ON COLUMN BIT_STATUS_MENSAJE.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN BIT_STATUS_MENSAJE.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN BIT_STATUS_MENSAJE.NOTAS IS 'Observaciones adicionales';
COMMIT;

-- ====================
-- Trigger Auditoria ESTADO_MENSAJES
-- ====================

CREATE OR REPLACE TRIGGER TRG_STATUS_MENSAJE_AUD
    AFTER INSERT OR UPDATE ON CAT_STATUS_MENSAJE
    FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

        -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_CREACION;

        -- Detectar borrado logico
        IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'ACTIVATE';
        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'DEACTIVATE';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;
    END IF;

    INSERT INTO BIT_STATUS_MENSAJE (
        ID_STATUS_MENSAJE_BIT,
        ID_STATUS_MENSAJE,
        NOMBRE_STATUS,
        DESCRIPTION,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS
    )
    VALUES (
               SYS_GUID(),
               :NEW.ID_STATUS_MENSAJE,
               :NEW.NOMBRE_STATUS,
               :NEW.DESCRIPTION,
               :NEW.ESTADO,
               V_FECHA_CREACION,
               :NEW.CREADO_POR,
               V_FECHA_MODIFICACION,
               FN_GET_IP,
               V_ACCION
           );
END;
/

INSERT INTO CAT_STATUS_MENSAJE (NOMBRE_STATUS, DESCRIPTION, CREADO_POR)
VALUES ('Recibido', 'Mensaje recibido por el Administrador', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_STATUS_MENSAJE (NOMBRE_STATUS, DESCRIPTION, CREADO_POR)
VALUES ('Leído', 'Mensaje leído por el Administrador', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_STATUS_MENSAJE (NOMBRE_STATUS, DESCRIPTION, CREADO_POR)
VALUES ('Contestado', 'Mensaje contestado por el Administrador', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');
COMMIT;

SELECT * FROM BIT_STATUS_MENSAJE;





--- *********************************************************************** Tabla BIT: CAT TIPO CLIENTES
BEGIN
    EXECUTE IMMEDIATE  'DROP TABLE BIT_TIPO_CLIENTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

---- Creando Tabla BIT
CREATE TABLE BIT_TIPO_CLIENTE(
       ID_TIPO_CLIENTE_BIT VARCHAR2(36) NOT NULL,
       ID_TIPO_CLIENTE VARCHAR2(15) NOT NULL,
       NOMBRE VARCHAR2(50) NOT NULL,
       DESCRIPTION VARCHAR2(100),
       ESTADO NUMBER(2) DEFAULT 1 NOT NULL,
       FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
       CREADO_POR VARCHAR2(36) NOT NULL,
       FECHA_ACTUALIZACION TIMESTAMP,
       ACTUALIZADO_POR VARCHAR2(36),
       NOTAS VARCHAR2(100),
       CONSTRAINT pk_id_type_clients_bit_type_clients_bit PRIMARY KEY (ID_TIPO_CLIENTE_BIT)
);

COMMENT ON TABLE BIT_TIPO_CLIENTE IS 'Tabla que de Bitacora que contiene la información de los TIPOS_CLIENTES';
COMMENT ON COLUMN BIT_TIPO_CLIENTE.ID_TIPO_CLIENTE_BIT IS 'ID_TIPO_CLIENTE_BIT de tabla TIPOS_CLIENTES';
COMMENT ON COLUMN BIT_TIPO_CLIENTE.ID_TIPO_CLIENTE IS 'ID del TIPO DEL CLIENTE';
COMMENT ON COLUMN BIT_TIPO_CLIENTE.NOMBRE IS 'Nombre del tipo de cliente';
COMMENT ON COLUMN BIT_TIPO_CLIENTE.DESCRIPTION IS 'Descripción del tipo de cliente';
COMMENT ON COLUMN BIT_TIPO_CLIENTE.ESTADO IS 'Estado del registro';
COMMENT ON COLUMN BIT_TIPO_CLIENTE.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN BIT_TIPO_CLIENTE.CREADO_POR IS 'Usuario Creador';
COMMENT ON COLUMN BIT_TIPO_CLIENTE.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN BIT_TIPO_CLIENTE.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN BIT_TIPO_CLIENTE.NOTAS IS 'Observaciones adicionales';
COMMIT;

-- ====================
-- Trigger Auditoria TIPO-CLIENTES
-- ====================

CREATE OR REPLACE TRIGGER TRG_TYPE_CLIENTS_AUD
    AFTER INSERT OR UPDATE ON CAT_TIPO_CLIENTE
    FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

        -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_CREACION;

        -- Detectar borrado logico
        IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'ACTIVATE';
        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'DEACTIVATE';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;
    END IF;

    INSERT INTO BIT_TIPO_CLIENTE (
        ID_TIPO_CLIENTE_BIT,
        ID_TIPO_CLIENTE,
        NOMBRE,
        DESCRIPTION,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS
    )
    VALUES (
               SYS_GUID(),
               :NEW.ID_TIPO_CLIENTE,
               :NEW.NOMBRE,
               :NEW.DESCRIPTION,
               :NEW.ESTADO,
               V_FECHA_CREACION,
               :NEW.CREADO_POR,
               V_FECHA_MODIFICACION,
               FN_GET_IP,
               V_ACCION
           );
END;
/

INSERT INTO CAT_TIPO_CLIENTE (NOMBRE, DESCRIPTION, CREADO_POR)
VALUES ('MORAL', 'Persona Moral o empresa', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_TIPO_CLIENTE (NOMBRE, DESCRIPTION, CREADO_POR)
VALUES ('FISICA', 'Persona Física', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_TIPO_CLIENTE (NOMBRE, DESCRIPTION, CREADO_POR)
VALUES ('GENERICO', 'Entidad que no se identifica como persona física o moral', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');
COMMIT;

SELECT * FROM BIT_TIPO_CLIENTE;




--- *********************************************************************** Tabla BIT: CAT TIPO CLIENTES
BEGIN
    EXECUTE IMMEDIATE  'DROP TABLE BIT_TIPO_TOKEN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

---- Creando Tabla BIT
CREATE TABLE BIT_TIPO_TOKEN(
       ID_TIPO_TOKEN_BIT VARCHAR2(36) NOT NULL,
       ID_TIPO_TOKEN VARCHAR2(15) NOT NULL,
       NOMBRE_TOKEN VARCHAR2(50) NOT NULL,
       DESCRIPTION VARCHAR2(100),
       ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
       FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
       CREADO_POR VARCHAR2(36) NOT NULL,
       FECHA_ACTUALIZACION TIMESTAMP,
       ACTUALIZADO_POR VARCHAR2(36),
       NOTAS VARCHAR2(100),
       CONSTRAINT pk_id_type_tokens_bit_type_tokens_bit PRIMARY KEY (ID_TIPO_TOKEN_BIT)
);

COMMENT ON TABLE BIT_TIPO_TOKEN IS 'Tabla que de Bitacora que contiene la información de los TIPOS_TOKENS';
COMMENT ON COLUMN BIT_TIPO_TOKEN.ID_TIPO_TOKEN_BIT IS 'ID_TIPO_TOKEN_BIT de tabla TIPOS_TOKENS';
COMMENT ON COLUMN BIT_TIPO_TOKEN.ID_TIPO_TOKEN IS 'ID del TIPO DEL TOKEN';
COMMENT ON COLUMN BIT_TIPO_TOKEN.NOMBRE_TOKEN IS 'Nombre del tipo de TOKEN';
COMMENT ON COLUMN BIT_TIPO_TOKEN.DESCRIPTION IS 'Descripción del tipo de TOKEN';
COMMENT ON COLUMN BIT_TIPO_TOKEN.ESTADO IS 'Estado del registro';
COMMENT ON COLUMN BIT_TIPO_TOKEN.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN BIT_TIPO_TOKEN.CREADO_POR IS 'Usuario Creador';
COMMENT ON COLUMN BIT_TIPO_TOKEN.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN BIT_TIPO_TOKEN.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN BIT_TIPO_TOKEN.NOTAS IS 'Observaciones adicionales';
COMMIT;

-- ====================
-- Trigger Auditoria TIPO-TOKENS
-- ====================

CREATE OR REPLACE TRIGGER TRG_TYPE_TOKENS_AUD
    AFTER INSERT OR UPDATE ON CAT_TIPO_TOKEN
    FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

        -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_CREACION;

        -- Detectar borrado logico
        IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'ACTIVATE';
        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'DEACTIVATE';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;
    END IF;

    INSERT INTO BIT_TIPO_TOKEN (
        ID_TIPO_TOKEN_BIT,
        ID_TIPO_TOKEN,
        NOMBRE_TOKEN,
        DESCRIPTION,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS
    )
    VALUES (
               SYS_GUID(),
               :NEW.ID_TIPO_TOKEN,
               :NEW.NOMBRE_TOKEN,
               :NEW.DESCRIPTION,
               :NEW.ESTADO,
               V_FECHA_CREACION,
               :NEW.CREADO_POR,
               V_FECHA_MODIFICACION,
               FN_GET_IP,
               V_ACCION
           );
END;
/

INSERT INTO CAT_TIPO_TOKEN (NOMBRE_TOKEN, DESCRIPTION, CREADO_POR)
VALUES ('EMAIL-VERIFY', 'VERIFICAR pERIFL DE USUARIO', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_TIPO_TOKEN (NOMBRE_TOKEN, DESCRIPTION, CREADO_POR)
VALUES ('RESET_PASSWORD', 'Cambio de Password', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_TIPO_TOKEN (NOMBRE_TOKEN, DESCRIPTION, CREADO_POR)
VALUES ('REACTIVACION', 'Reactivar cuenta', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');
COMMIT;

SELECT * FROM BIT_TIPO_TOKEN;




--- *********************************************************************** Tabla BIT: CLIENTES
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BIT_CLIENTES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

---- Creando Tabla BIT
CREATE TABLE BIT_CLIENTES(
       ID_CLIENTES_BIT VARCHAR2(36) NOT NULL,
       ID_CLIENTE VARCHAR2(15) NOT NULL,
       NOMBRE VARCHAR2(50) NOT NULL,
       APATERNO VARCHAR2(40) NOT NULL,
       AMATERNO VARCHAR2(40),
       EMAIL VARCHAR2(100),
       FECHA_ALTA DATE DEFAULT SYSDATE,
       ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
       FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
       CREADO_POR VARCHAR2(36) NOT NULL,
       FECHA_ACTUALIZACION TIMESTAMP,
       ACTUALIZADO_POR VARCHAR2(36),
       NOTAS VARCHAR2(100),
       ACCION VARCHAR2(10) NOT NULL,
       IP VARCHAR2(30) NOT NULL,
       CONSTRAINT pk_id_clients_bit_clients_bit PRIMARY KEY (ID_CLIENTES_BIT)
);

COMMENT ON TABLE BIT_CLIENTES IS 'Tabla que de Bitacora que contiene la información de los CLIENTES';
COMMENT ON COLUMN BIT_CLIENTES.ID_CLIENTES_BIT IS 'ID_CLIENTES_BIT de tabla CLIENTES';
COMMENT ON COLUMN BIT_CLIENTES.ID_CLIENTE IS 'Llave primaria de la tabla Clientes';
COMMENT ON COLUMN BIT_CLIENTES.NOMBRE IS 'Nombre del cliente';
COMMENT ON COLUMN BIT_CLIENTES.APATERNO IS 'Apellido Paterno del cliente';
COMMENT ON COLUMN BIT_CLIENTES.AMATERNO IS 'Apellido Materno del cliente';
COMMENT ON COLUMN BIT_CLIENTES.EMAIL IS 'Correo del cliente';
COMMENT ON COLUMN BIT_CLIENTES.FECHA_ALTA IS 'Fecha de alta del cliente';
COMMENT ON COLUMN BIT_CLIENTES.ESTADO IS 'Bandera para borrado logico';
COMMENT ON COLUMN BIT_CLIENTES.FECHA_CREACION IS 'fecha creción';
COMMENT ON COLUMN BIT_CLIENTES.CREADO_POR IS 'usuario creador';
COMMENT ON COLUMN BIT_CLIENTES.FECHA_ACTUALIZACION IS 'fecha de actualización';
COMMENT ON COLUMN BIT_CLIENTES.ACTUALIZADO_POR IS 'Usuario que actualizo';
COMMENT ON COLUMN BIT_CLIENTES.NOTAS IS 'Observaciones adicionales';
COMMENT ON COLUMN BIT_CLIENTES.ACCION IS 'Campos de control que indicala Accción en el registro';
COMMENT ON COLUMN BIT_CLIENTES.IP IS 'Campo de control que indica IP de donde se solicito operación en el registro';
COMMIT;

-- ====================
-- Trigger Auditoria CLIENTES
-- ====================

CREATE OR REPLACE TRIGGER TRG_CLIENTES_AUD
    AFTER INSERT OR UPDATE ON CLIENTES
    FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

        -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_ALTA;

        -- Detectar borrado logico
        IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'DEACTIVATE';
        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'ACTIVATE';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;
    END IF;

    INSERT INTO BIT_CLIENTES (
        ID_CLIENTES_BIT,
        ID_CLIENTE,
        NOMBRE,
        APATERNO,
        AMATERNO,
        EMAIL,
        FECHA_ALTA,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS,
        ACCION,
        IP
    )
    VALUES (
            SYS_GUID(),
            :NEW.ID_CLIENTE,
            :NEW.NOMBRE,
            :NEW.APATERNO,
            :NEW.AMATERNO,
            :NEW.EMAIL,
            :NEW.FECHA_ALTA,
            :NEW.ESTADO,
            V_FECHA_CREACION,
            :NEW.CREADO_POR,
            V_FECHA_MODIFICACION,
            :NEW.ACTUALIZADO_POR,
            :NEW.NOTAS,
            V_ACCION,
            FN_GET_IP
           );
END;
/

/****
  INSERT INTO CAT_TIPO_TOKEN (NOMBRE_TOKEN, DESCRIPTION, CREADO_POR)
VALUES ('EMAIL-VERIFY', 'VERIFICAR pERIFL DE USUARIO', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_TIPO_TOKEN (NOMBRE_TOKEN, DESCRIPTION, CREADO_POR)
VALUES ('RESET_PASSWORD', 'Cambio de Password', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_TIPO_TOKEN (NOMBRE_TOKEN, DESCRIPTION, CREADO_POR)
VALUES ('REACTIVACION', 'Reactivar cuenta', '57e8cc9c-9d83-4e76-99c1-d6de3d7a984e');
COMMIT;
  ****/

--- SELECT * FROM BIT_CLIENTES;






--- *********************************************************************** Tabla BIT: DATOS_FISCALES
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BIT_DATOS_FISCALES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

---- Creando Tabla BIT
CREATE TABLE BIT_DATOS_FISCALES(
       ID_DATOSFISC_BIT VARCHAR2(36) NOT NULL,
       ID_DATOSFIC VARCHAR2(36) NOT NULL,
       ID_CLIENTE VARCHAR2(36) NOT NULL,
       RAZON_SOCIAL VARCHAR2(150) NOT NULL,
       RFC VARCHAR2(13) NOT NULL,
       CODIGO_POSTAL VARCHAR2(5) NOT NULL,
       ID_TIPO_CLIENTE VARCHAR2(3) NOT NULL,
       USO_CFDI VARCHAR2(3) NOT NULL,
       EMAIL VARCHAR2(100),
       D_ESTADO VARCHAR2(36) NOT NULL,
       D_CIUDAD VARCHAR2(36) NOT NULL,
       D_COLONIA VARCHAR2(36) NOT NULL,
       D_ZONA VARCHAR2(36) NOT NULL,
       FECHA_ALTA DATE DEFAULT SYSDATE,
       ESTADO NUMBER(2) NOT NULL,
       CREADO_POR VARCHAR2(36) NOT NULL,
       FECHA_ACTUALIZACION TIMESTAMP,
       ACTUALIZADO_POR VARCHAR2(36),
       NOTAS VARCHAR2(100),
       CONSTRAINT pk_id_datosFiscales_bit PRIMARY KEY (ID_DATOSFISC_BIT)
);

COMMENT ON TABLE BIT_DATOS_FISCALES IS 'Tabla que de Bitacora que contiene la información de los datos fiscales';
COMMENT ON COLUMN BIT_DATOS_FISCALES.ID_DATOSFISC_BIT IS 'ID_DATOSFISC_BIT de tabla de DATOS FISCALES';
COMMENT ON COLUMN BIT_DATOS_FISCALES.ID_DATOSFIC IS 'Llave primaria de la tabla';
COMMENT ON COLUMN BIT_DATOS_FISCALES.ID_CLIENTE IS 'Identificador único interno (CLI-XXXXX)';
COMMENT ON COLUMN BIT_DATOS_FISCALES.RAZON_SOCIAL IS 'Nombre o Denominación Sicual EXACTA como en la Constancia de Situación Fiscal';
COMMENT ON COLUMN BIT_DATOS_FISCALES.RFC IS 'Registro Federal de Contribuyentes';
COMMENT ON COLUMN BIT_DATOS_FISCALES.CODIGO_POSTAL IS 'Domicilio Fiscal del receptor (5 digitos)';
COMMENT ON COLUMN BIT_DATOS_FISCALES.ID_TIPO_CLIENTE IS 'Clave del regimen tibutario del cliente';
COMMENT ON COLUMN BIT_DATOS_FISCALES.USO_CFDI IS 'uso del CFDI';
COMMENT ON COLUMN BIT_DATOS_FISCALES.EMAIL IS 'Email del cliente';
COMMENT ON COLUMN BIT_DATOS_FISCALES.D_ESTADO IS 'Descripción del estado';
COMMENT ON COLUMN BIT_DATOS_FISCALES.D_CIUDAD IS 'Descripción de la ciudad';
COMMENT ON COLUMN BIT_DATOS_FISCALES.D_COLONIA IS 'Descripción de la colonia';
COMMENT ON COLUMN BIT_DATOS_FISCALES.D_ZONA IS 'Descripción de la zona';
COMMENT ON COLUMN BIT_DATOS_FISCALES.FECHA_ALTA IS 'Fecha de creación del registro';
COMMENT ON COLUMN BIT_DATOS_FISCALES.ESTADO IS 'Bandera para borrado logico (1 = Activo | 0 = Inactivo)';
COMMENT ON COLUMN BIT_DATOS_FISCALES.CREADO_POR IS 'Usuario Creador';
COMMENT ON COLUMN BIT_DATOS_FISCALES.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN BIT_DATOS_FISCALES.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN BIT_DATOS_FISCALES.NOTAS IS 'Observaciones adicionales';

-- ====================
-- Trigger Auditoria DATOS_FISCALES
-- ====================

CREATE OR REPLACE TRIGGER TRG_DATOS_FIC_AUD
    AFTER INSERT OR UPDATE ON DATOS_FISCALES
    FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

        -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_ALTA;

        -- Detectar borrado logico
        IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'DEACTIVATE';
        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'ACTIVATE';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;
    END IF;

    INSERT INTO BIT_DATOS_FISCALES (
        ID_DATOSFISC_BIT,
        ID_DATOSFIC,
        ID_CLIENTE,
        RAZON_SOCIAL,
        RFC,
        CODIGO_POSTAL,
        ID_TIPO_CLIENTE,
        USO_CFDI,
        EMAIL,
        D_ESTADO,
        D_CIUDAD,
        D_COLONIA,
        D_ZONA,
        FECHA_ALTA,
        ESTADO,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS
    )
    VALUES (
            SYS_GUID(),
            :NEW.ID_DATOSFIC,
            :NEW.ID_CLIENTE,
            :NEW.RAZON_SOCIAL,
            :NEW.RFC,
            :NEW.CODIGO_POSTAL,
            :NEW.ID_TIPO_CLIENTE,
            :NEW.USO_CFDI,
            :NEW.EMAIL,
            :NEW.D_ESTADO,
            :NEW.D_CIUDAD,
            :NEW.D_COLONIA,
            :NEW.D_ZONA,
            V_FECHA_CREACION,
            :NEW.ESTADO,
            FN_GET_IP,
            V_FECHA_MODIFICACION,
            :NEW.ACTUALIZADO_POR,
            V_ACCION
           );
END;
/

--- SELECT * FROM BIT_DATOS_FISCALES;





--- *********************************************************************** Tabla BIT: FACTURAS

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BIT_FACTURAS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE BIT_FACTURAS(
    ID_FACTURA_BIT VARCHAR2(36) NOT NULL,
    ID_FACTURA VARCHAR2(36) NOT NULL,
    ID_CLIENTE VARCHAR2(36) NOT NULL,
    MONTO_TOTAL NUMBER(10,2) NOT NULL,
    FOLIO NUMBER NOT NULL,
    ANIO NUMBER(4) NOT NULL,
    ID_ESTADO_FACTURA VARCHAR2(15) NOT NULL,
    FECHA_FACTURA DATE DEFAULT SYSDATE,
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_ID_FACTURA_FACTURAS_BIT PRIMARY KEY (ID_FACTURA_BIT)
);

COMMENT ON TABLE BIT_FACTURAS IS 'Tabla que contiene la información de las facturas de los clientes';
COMMENT ON COLUMN BIT_FACTURAS.ID_FACTURA_BIT IS 'ID_DATOSFISC_BIT de tabla de FACTURACIONES';
COMMENT ON COLUMN BIT_FACTURAS.ID_FACTURA IS 'Llave primaria de la tabla Facturas';
COMMENT ON COLUMN BIT_FACTURAS.ID_CLIENTE IS 'Llave foranea del cliente';
COMMENT ON COLUMN BIT_FACTURAS.MONTO_TOTAL IS 'Monto total de la factura';
COMMENT ON COLUMN BIT_FACTURAS.FOLIO IS 'Folio consecutivo por año';
COMMENT ON COLUMN BIT_FACTURAS.ANIO IS 'Año de la factura';
COMMENT ON COLUMN BIT_FACTURAS.ID_ESTADO_FACTURA IS 'ID estado de la factura';
COMMENT ON COLUMN BIT_FACTURAS.FECHA_FACTURA IS 'Fecha de la factura';
COMMENT ON COLUMN BIT_FACTURAS.ESTADO IS 'Bandera para borrado logico';
COMMENT ON COLUMN BIT_FACTURAS.CREADO_POR IS 'Usuario Creador';
COMMENT ON COLUMN BIT_FACTURAS.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN BIT_FACTURAS.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN BIT_FACTURAS.NOTAS IS 'Observaciones adicionales';
COMMIT;

-- ====================
-- Trigger Auditoria FACTURAS
-- ====================

CREATE OR REPLACE TRIGGER TRG_FACTURAS_AUD
    AFTER INSERT OR UPDATE ON FACTURAS
    FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

        -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_FACTURA;

        -- Detectar borrado logico
        IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'DEACTIVATE';
        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'ACTIVATE';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;
    END IF;

    INSERT INTO BIT_FACTURAS (
        ID_FACTURA_BIT,
        ID_FACTURA,
        ID_CLIENTE,
        MONTO_TOTAL,
        FOLIO,
        ANIO,
        ID_ESTADO_FACTURA,
        FECHA_FACTURA,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS
    )
    VALUES (
               SYS_GUID(),
               :NEW.ID_FACTURA,
               :NEW.ID_CLIENTE,
               :NEW.MONTO_TOTAL,
               :NEW.FOLIO,
               :NEW.ANIO,
               :NEW.ID_ESTADO_FACTURA,
               :NEW.FECHA_FACTURA,
               :NEW.ESTADO,
               V_FECHA_CREACION,
               :NEW.CREADO_POR,
               V_FECHA_MODIFICACION,
               FN_GET_IP,
               V_ACCION
           );
END;
/

--- SELECT * FROM BIT_FACTURAS;





--- *********************************************************************** Tabla BIT: MENSAJES CONTACTO

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BIT_MENSAJE_CONTACTO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE BIT_MENSAJE_CONTACTO(
     ID_MENSAJE_BIT VARCHAR2(36) NOT NULL,
     ID_MENSAJE VARCHAR2(36) NOT NULL,
     NOMBRE VARCHAR2(40) NOT NULL,
     CORREO VARCHAR2(60) NOT NULL,
     DESCRIPTION VARCHAR2(1000) NOT NULL,
     ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
     FECHA_ENVIO DATE DEFAULT SYSDATE,
     ID_STATUS_MENSAJE VARCHAR2(15) DEFAULT 1 NOT NULL,
     USUARIO_RESPUESTA VARCHAR2(40) DEFAULT 'NINGUNO' NOT NULL,
     ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
     FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
     CREADO_POR VARCHAR2(36) NOT NULL,
     FECHA_ACTUALIZACION TIMESTAMP,
     ACTUALIZADO_POR VARCHAR2(36),
     NOTAS VARCHAR2(100),
     CONSTRAINT PK_ID_MENSAJE_BIT PRIMARY KEY (ID_MENSAJE_BIT)
);

COMMENT ON TABLE BIT_MENSAJE_CONTACTO IS 'Tabla que contiene la información de los mensajes de contacto';
COMMENT ON COLUMN BIT_MENSAJE_CONTACTO.ID_MENSAJE_BIT IS 'ID_MENSAJE_BIT de tabla de Mensajes de Contacto';
COMMENT ON COLUMN BIT_MENSAJE_CONTACTO.ID_MENSAJE IS 'ID de mensaje';
COMMENT ON COLUMN BIT_MENSAJE_CONTACTO.NOMBRE IS 'Nombre del usuario';
COMMENT ON COLUMN BIT_MENSAJE_CONTACTO.CORREO IS 'Correo del usuario';
COMMENT ON COLUMN BIT_MENSAJE_CONTACTO.DESCRIPTION IS 'Descripción del mensaje';
COMMENT ON COLUMN BIT_MENSAJE_CONTACTO.ACTIVO IS 'Bandera de activo';
COMMENT ON COLUMN BIT_MENSAJE_CONTACTO.FECHA_ENVIO IS 'Fecha de envio del mensaje';
COMMENT ON COLUMN BIT_MENSAJE_CONTACTO.ID_STATUS_MENSAJE IS 'Estado el mensaje';
COMMENT ON COLUMN BIT_MENSAJE_CONTACTO.USUARIO_RESPUESTA IS 'Usuario que responde';
COMMENT ON COLUMN BIT_MENSAJE_CONTACTO.ESTADO IS 'Bandera para borrado logico';
COMMENT ON COLUMN BIT_MENSAJE_CONTACTO.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN BIT_MENSAJE_CONTACTO.CREADO_POR IS 'Usuario Creador';
COMMENT ON COLUMN BIT_MENSAJE_CONTACTO.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN BIT_MENSAJE_CONTACTO.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN BIT_MENSAJE_CONTACTO.NOTAS IS 'Observaciones adicionales';

COMMIT;

-- ====================
-- Trigger Auditoria MENSAJES DE CONTACTO
-- ====================

CREATE OR REPLACE TRIGGER TRG_MNSJ_CONTACTO_AUD
    AFTER INSERT OR UPDATE ON MENSAJE_CONTACTO
    FOR EACH ROW
DECLARE
    V_ACCION VARCHAR2(20);
    V_FECHA_CREACION DATE := NULL;
    V_FECHA_MODIFICACION DATE := NULL;
BEGIN

    -- INSERT
    IF INSERTING THEN
        V_ACCION := 'INSERT';
        V_FECHA_CREACION := SYSDATE;

        -- UPDATE
    ELSIF UPDATING THEN
        V_FECHA_MODIFICACION := SYSDATE;
        V_FECHA_CREACION := :OLD.FECHA_ENVIO;

        -- Detectar borrado logico
        IF :OLD.ESTADO = 1 AND :NEW.ESTADO = 0 THEN
            V_ACCION := 'DEACTIVATE';
        ELSIF :OLD.ESTADO = 0 AND :NEW.ESTADO = 1 THEN
            V_ACCION := 'ACTIVATE';
        ELSE
            V_ACCION := 'UPDATE';
        END IF;
    END IF;

    INSERT INTO BIT_MENSAJE_CONTACTO (
        ID_MENSAJE_BIT,
        ID_MENSAJE,
        NOMBRE,
        CORREO,
        DESCRIPTION,
        ACTIVO,
        FECHA_ENVIO,
        ID_STATUS_MENSAJE,
        USUARIO_RESPUESTA,
        ESTADO,
        FECHA_CREACION,
        CREADO_POR,
        FECHA_ACTUALIZACION,
        ACTUALIZADO_POR,
        NOTAS
    )
    VALUES (
        SYS_GUID(),
        :NEW.ID_MENSAJE,
        :NEW.NOMBRE,
        :NEW.CORREO,
        :NEW.DESCRIPTION,
        :NEW.ACTIVO,
        :NEW.FECHA_ENVIO,
        :NEW.ID_STATUS_MENSAJE,
        :NEW.USUARIO_RESPUESTA,
        :NEW.ESTADO,
        V_FECHA_CREACION,
        :NEW.CREADO_POR,
        V_FECHA_MODIFICACION,
        FN_GET_IP,
        V_ACCION
           );
END;
/

--- SELECT * FROM BIT_MENSAJE_CONTACTO;