alter session set current_schema = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CAT_TIPO_TOKEN CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TIPO_TOKEN_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CAT_TIPO_TOKEN(
       ID_TIPO_TOKEN VARCHAR2(15) NOT NULL,
       NOMBRE_TOKEN VARCHAR2(50) NOT NULL,
       DESCRIPTION VARCHAR2(100),
       ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
       FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
       CREADO_POR VARCHAR2(36) NOT NULL,
       FECHA_ACTUALIZACION TIMESTAMP,
       ACTUALIZADO_POR VARCHAR2(36),
       NOTAS VARCHAR2(100),
       CONSTRAINT PK_TIPO_TOKEN PRIMARY KEY (ID_TIPO_TOKEN),
       CONSTRAINT CK_ESTADO_TOKEN CHECK (ESTADO IN (0, 99))
);

COMMENT ON TABLE CAT_TIPO_TOKEN IS 'Tabla que contiene los estados de los TIPOS DE TOKENS';
COMMENT ON COLUMN CAT_TIPO_TOKEN.ID_TIPO_TOKEN IS 'ID del TIPO DEL TOKEN';
COMMENT ON COLUMN CAT_TIPO_TOKEN.NOMBRE_TOKEN IS 'Nombre del tipo de TOKEN';
COMMENT ON COLUMN CAT_TIPO_TOKEN.DESCRIPTION IS 'Descripción del tipo de TOKEN';
COMMENT ON COLUMN CAT_TIPO_TOKEN.ESTADO IS 'Estado del registro';
COMMENT ON COLUMN CAT_TIPO_TOKEN.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN CAT_TIPO_TOKEN.CREADO_POR IS 'Usuario Creador';
COMMENT ON COLUMN CAT_TIPO_TOKEN.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN CAT_TIPO_TOKEN.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN CAT_TIPO_TOKEN.NOTAS IS 'Observaciones adicionales';
COMMIT;

CREATE SEQUENCE SEQ_TIPO_TOKEN_ID START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_TIPO_TOKEN_ID
    BEFORE INSERT ON CAT_TIPO_TOKEN
    FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPO_TOKEN IS NULL THEN
        :NEW.ID_TIPO_TOKEN := 'CTK-' || LPAD(SEQ_TIPO_TOKEN_ID.NEXTVAL, 3, '0');
    END IF;
END;

