alter session set current_schema = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTE_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CLIENTES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CLIENTES(
    ID_CLIENTE VARCHAR2(15) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    APATERNO VARCHAR2(40) NOT NULL,
    AMATERNO VARCHAR2(40),
    EMAIL VARCHAR2(100),
    FECHA_ALTA DATE DEFAULT SYSDATE,
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT pk_id_cliente_clientes PRIMARY KEY (ID_CLIENTE)
);

COMMENT ON TABLE CLIENTES IS 'Tabla que contiene la información de los CLIENTES';
COMMENT ON COLUMN CLIENTES.ID_CLIENTE IS 'Llave primaria de la tabla Clientes';
COMMENT ON COLUMN CLIENTES.NOMBRE IS 'Nombre del cliente';
COMMENT ON COLUMN CLIENTES.APATERNO IS 'Apellido Paterno del cliente';
COMMENT ON COLUMN CLIENTES.AMATERNO IS 'Apellido Materno del cliente';
COMMENT ON COLUMN CLIENTES.EMAIL IS 'Correo del cliente';
COMMENT ON COLUMN CLIENTES.FECHA_ALTA IS 'Fecha de alta del cliente';
COMMENT ON COLUMN CLIENTES.ESTADO IS 'Bandera para borrado logico';
COMMENT ON COLUMN CLIENTES.FECHA_CREACION IS 'fecha creción';
COMMENT ON COLUMN CLIENTES.CREADO_POR IS 'usuario creador';
COMMENT ON COLUMN CLIENTES.FECHA_ACTUALIZACION IS 'fecha de actualización';
COMMENT ON COLUMN CLIENTES.ACTUALIZADO_POR IS 'Usuario que actualizo';
COMMENT ON COLUMN CLIENTES.NOTAS IS 'Observaciones adicionales';
COMMIT;

CREATE SEQUENCE SEQ_CLIENTE_ID START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_CLIENTE_ID
    BEFORE INSERT ON CLIENTES
    FOR EACH ROW
BEGIN
    IF :NEW.ID_CLIENTE IS NULL THEN
        :NEW.ID_CLIENTE := 'CLI-' || LPAD(SEQ_CLIENTE_ID.NEXTVAL, 6, '0');
    END IF;
END;