alter session set current_schema = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DATOSFIC_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DATOS_FISCALES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE DATOS_FISCALES(
        ID_DATOSFIC VARCHAR2(36) NOT NULL,
        ID_CLIENTE VARCHAR2(36) NOT NULL,
        RAZON_SOCIAL VARCHAR2(150) NOT NULL,
        RFC VARCHAR2(13) NOT NULL,
        CODIGO_POSTAL VARCHAR2(5) NOT NULL,
        ID_TIPO_CLIENTE VARCHAR2(3) NOT NULL,
        USO_CFDI VARCHAR2(3) NOT NULL,
        EMAIL VARCHAR2(100),
        D_ESTADO VARCHAR2(36) NOT NULL,
        D_CIUDAD VARCHAR2(36) NOT NULL,
        D_COLONIA VARCHAR2(36) NOT NULL,
        D_ZONA VARCHAR2(36) NOT NULL,
        FECHA_ALTA DATE DEFAULT SYSDATE,
        ESTADO NUMBER(2) NOT NULL,
        CREADO_POR VARCHAR2(36) NOT NULL,
        FECHA_ACTUALIZACION TIMESTAMP,
        ACTUALIZADO_POR VARCHAR2(36),
        NOTAS VARCHAR2(100),
        CONSTRAINT pk_id_datosFiscales_clientes PRIMARY KEY (ID_DATOSFIC)
);

COMMENT ON TABLE DATOS_FISCALES IS 'Tabla que contiene la información de los clientes para facturación CFDI 4.0';
COMMENT ON COLUMN DATOS_FISCALES.ID_DATOSFIC IS 'Llave primaria de la tabla';
COMMENT ON COLUMN DATOS_FISCALES.ID_CLIENTE IS 'Identificador único interno (CLI-XXXXX)';
COMMENT ON COLUMN DATOS_FISCALES.RAZON_SOCIAL IS 'Nombre o Denominación Sicual EXACTA como en la Constancia de Situación Fiscal';
COMMENT ON COLUMN DATOS_FISCALES.RFC IS 'Registro Federal de Contribuyentes';
COMMENT ON COLUMN DATOS_FISCALES.CODIGO_POSTAL IS 'Domicilio Fiscal del receptor (5 digitos)';
COMMENT ON COLUMN DATOS_FISCALES.ID_TIPO_CLIENTE IS 'Clave del regimen tibutario del cliente';
COMMENT ON COLUMN DATOS_FISCALES.USO_CFDI IS 'uso del CFDI';
COMMENT ON COLUMN DATOS_FISCALES.EMAIL IS 'Email del cliente';
COMMENT ON COLUMN DATOS_FISCALES.D_ESTADO IS 'Descripción del estado';
COMMENT ON COLUMN DATOS_FISCALES.D_CIUDAD IS 'Descripción de la ciudad';
COMMENT ON COLUMN DATOS_FISCALES.D_COLONIA IS 'Descripción de la colonia';
COMMENT ON COLUMN DATOS_FISCALES.D_ZONA IS 'Descripción de la zona';
COMMENT ON COLUMN DATOS_FISCALES.FECHA_ALTA IS 'Fecha de creación del registro';
COMMENT ON COLUMN DATOS_FISCALES.ESTADO IS 'Bandera para borrado logico (1 = Activo | 0 = Inactivo)';
COMMENT ON COLUMN DATOS_FISCALES.CREADO_POR IS 'Usuario Creador';
COMMENT ON COLUMN DATOS_FISCALES.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN DATOS_FISCALES.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN DATOS_FISCALES.NOTAS IS 'Observaciones adicionales';

COMMIT;

CREATE SEQUENCE SEQ_DATOSFIC_ID START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_DATOSFIC_ID
    BEFORE INSERT ON DATOS_FISCALES
    FOR EACH ROW
BEGIN
    IF :NEW.ID_DATOSFIC IS NULL THEN
        :NEW.ID_DATOSFIC := 'DATAFIC-' || LPAD(SEQ_DATOSFIC_ID.NEXTVAL, 6, '0');
    END IF;
END;