alter session set current_schema = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FACTURA_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE FACTURAS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE FACTURAS(
    ID_FACTURA VARCHAR2(36) NOT NULL,
    ID_CLIENTE VARCHAR2(36) NOT NULL,
    MONTO_TOTAL NUMBER(10,2) NOT NULL,
    FOLIO NUMBER NOT NULL,
    ANIO NUMBER(4) NOT NULL,
    ID_ESTADO_FACTURA VARCHAR2(15) NOT NULL,
    FECHA_FACTURA DATE DEFAULT SYSDATE,
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_ID_FACTURA_FACTURAS PRIMARY KEY (ID_FACTURA),
    CONSTRAINT FK_ID_CLIENTE_FACTURAS FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
    CONSTRAINT FK_ID_ESTADO_FACTURAS FOREIGN KEY (ID_ESTADO_FACTURA) REFERENCES CAT_ESTADO_FACTURA (ID_ESTADO_FACTURA)
);

COMMENT ON TABLE FACTURAS IS 'Tabla que contiene la información de las facturas de los clientes';
COMMENT ON COLUMN FACTURAS.ID_FACTURA IS 'Llave primaria de la tabla Facturas';
COMMENT ON COLUMN FACTURAS.ID_CLIENTE IS 'Llave foranea del cliente';
COMMENT ON COLUMN FACTURAS.MONTO_TOTAL IS 'Monto total de la factura';
COMMENT ON COLUMN FACTURAS.FOLIO IS 'Folio consecutivo por año';
COMMENT ON COLUMN FACTURAS.ANIO IS 'Año de la factura';
COMMENT ON COLUMN FACTURAS.ID_ESTADO_FACTURA IS 'ID estado de la factura';
COMMENT ON COLUMN FACTURAS.FECHA_FACTURA IS 'Fecha de la factura';
COMMENT ON COLUMN FACTURAS.ESTADO IS 'Bandera para borrado logico';
COMMENT ON COLUMN FACTURAS.CREADO_POR IS 'Usuario Creador';
COMMENT ON COLUMN FACTURAS.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN FACTURAS.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN FACTURAS.NOTAS IS 'Observaciones adicionales';
COMMIT;

CREATE SEQUENCE SEQ_FACTURA_ID
START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_FACTURA_ID
    BEFORE INSERT ON FACTURAS
    FOR EACH ROW
BEGIN
    IF :NEW.ID_FACTURA IS NULL THEN
        :NEW.ID_FACTURA := 'FAC-' || :NEW.ANIO || LPAD(SEQ_FACTURA_ID.NEXTVAL, 3, '0');
    END IF;
END;