alter session set current_schema = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MENSAJE_CONTACTO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MENSAJE_CONTACTO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE MENSAJE_CONTACTO(
     ID_MENSAJE VARCHAR2(36) NOT NULL,
     NOMBRE VARCHAR2(40) NOT NULL,
     CORREO VARCHAR2(60) NOT NULL,
     DESCRIPTION VARCHAR2(1000) NOT NULL,
     ACTIVO NUMBER(1) DEFAULT 1 NOT NULL,
     FECHA_ENVIO DATE DEFAULT SYSDATE,
     ID_STATUS_MENSAJE VARCHAR2(15) DEFAULT 1 NOT NULL,
     USUARIO_RESPUESTA VARCHAR2(40) DEFAULT 'NINGUNO' NOT NULL,
     ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
     FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
     CREADO_POR VARCHAR2(36) NOT NULL,
     FECHA_ACTUALIZACION TIMESTAMP,
     ACTUALIZADO_POR VARCHAR2(36),
     NOTAS VARCHAR2(100),
     CONSTRAINT PK_ID_MENSAJE PRIMARY KEY (ID_MENSAJE),
     CONSTRAINT FK_ID_ESTATUS_MENSAJE
         FOREIGN KEY (ID_STATUS_MENSAJE)
             REFERENCES CAT_STATUS_MENSAJE (ID_STATUS_MENSAJE)
);

COMMENT ON TABLE MENSAJE_CONTACTO IS 'Tabla que contiene la información de los mensajes de contacto';
COMMENT ON COLUMN MENSAJE_CONTACTO.ID_MENSAJE IS 'ID de mensaje';
COMMENT ON COLUMN MENSAJE_CONTACTO.NOMBRE IS 'Nombre del usuario';
COMMENT ON COLUMN MENSAJE_CONTACTO.CORREO IS 'Correo del usuario';
COMMENT ON COLUMN MENSAJE_CONTACTO.DESCRIPTION IS 'Descripción del mensaje';
COMMENT ON COLUMN MENSAJE_CONTACTO.ACTIVO IS 'Bandera de activo';
COMMENT ON COLUMN MENSAJE_CONTACTO.FECHA_ENVIO IS 'Fecha de envio del mensaje';
COMMENT ON COLUMN MENSAJE_CONTACTO.ID_STATUS_MENSAJE IS 'Estado el mensaje';
COMMENT ON COLUMN MENSAJE_CONTACTO.USUARIO_RESPUESTA IS 'Usuario que responde';
COMMENT ON COLUMN MENSAJE_CONTACTO.ESTADO IS 'Bandera para borrado logico';
COMMENT ON COLUMN MENSAJE_CONTACTO.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN MENSAJE_CONTACTO.CREADO_POR IS 'Usuario Creador';
COMMENT ON COLUMN MENSAJE_CONTACTO.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN MENSAJE_CONTACTO.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN MENSAJE_CONTACTO.NOTAS IS 'Observaciones adicionales';

COMMIT;

CREATE SEQUENCE SEQ_MENSAJE_CONTACTO
    START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_MSJ_CONTACTO_ID
    BEFORE INSERT ON MENSAJE_CONTACTO
    FOR EACH ROW
BEGIN
    IF :NEW.ID_MENSAJE IS NULL THEN
        :NEW.ID_MENSAJE := 'MCTCT-' || LPAD(SEQ_MENSAJE_CONTACTO.NEXTVAL, 3, '0');
    END IF;
END;
