alter session set current_schema = SECURITY;

---- BIT_PAGOS

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PAGO_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PAGOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PAGOS(
    ID_PAGO VARCHAR2(36) NOT NULL,
    ID_FACTURA VARCHAR2(36) NOT NULL,
    MONTO NUMBER(10,2) NOT NULL,
    ID_ESTADO_PAGO VARCHAR2(15) NOT NULL,
    FECHA_PAGO DATE DEFAULT SYSDATE,
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT pk_id_pago_pagos PRIMARY KEY (ID_PAGO),
    CONSTRAINT fk_id_factura_pagos FOREIGN KEY (ID_FACTURA) REFERENCES FACTURAS(ID_FACTURA),
    CONSTRAINT fk_id_estado_pago FOREIGN KEY (ID_ESTADO_PAGO) REFERENCES CAT_ESTADO_PAGO(ID_ESTADO_PAGO)
);

COMMENT ON TABLE PAGOS IS 'Tabla que contiene los Pagos totales o Parciales de una factura';
COMMENT ON COLUMN PAGOS.ID_PAGO IS 'Llave primaria de la tabla Pagos';
COMMENT ON COLUMN PAGOS.ID_FACTURA IS 'Llave foranea ID_FACTURA que hace refrencia a la tabla FACTURAS';
COMMENT ON COLUMN PAGOS.MONTO IS 'Monto del Pago de la Factura';
COMMENT ON COLUMN PAGOS.ID_ESTADO_PAGO IS 'ID del Estado de pago de la factura';
COMMENT ON COLUMN PAGOS.FECHA_PAGO IS 'Fecha de pago de la Factura';
COMMENT ON COLUMN PAGOS.ESTADO IS 'Bandera pra borrado logico';
COMMENT ON COLUMN PAGOS.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN PAGOS.CREADO_POR IS 'Usuario creador';
COMMENT ON COLUMN PAGOS.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN PAGOS.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN PAGOS.NOTAS IS 'Observaciones adicionales';
COMMIT;

CREATE SEQUENCE SEQ_PAGO_ID START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999 NOCACHE CYCLE;

CREATE OR REPLACE TRIGGER TRG_PAGO_ID
BEFORE INSERT ON PAGOS
FOR EACH ROW
BEGIN
    IF :NEW.ID_PAGO IS NULL THEN
        :NEW.ID_PAGO := 'PAG-' || :NEW.FECHA_PAGO || LPAD(SEQ_PAGO_ID.NEXTVAL, 3, '0');
    END IF;
END;
/