alter session set current_schema = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PERSONA_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE PERSONAS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE PERSONAS(
        ID_PERSONA VARCHAR2(20) NOT NULL,
        NOMBRE VARCHAR2(100) NOT NULL,
        APATERNO VARCHAR(100) NOT NULL,
        AMATERNO VARCHAR2(100) NOT NULL,
        TELEFONO VARCHAR2(20),
        CORREO VARCHAR2(100) NOT NULL,
        UUDI_CIUDAD VARCHAR2(36) NOT NULL,
        UUDI_ESTADO VARCHAR2(36) NOT NULL,
        ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
        FECHA_ALTA  DATE DEFAULT SYSDATE,
        VERIFICADO NUMBER(2) DEFAULT 0 NOT NULL,
        FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CREADO_POR VARCHAR2(36) NOT NULL,
        FECHA_ACTUALIZACION TIMESTAMP,
        ACTUALIZADO_POR VARCHAR2(36),
        NOTAS VARCHAR2(100),
        CONSTRAINT pk_persona PRIMARY KEY (ID_PERSONA),
        CONSTRAINT uk_persona_correo UNIQUE (CORREO),
        CONSTRAINT fk_cat_persona_estado FOREIGN KEY (UUDI_ESTADO)
        REFERENCES CAT_ESTADO(UUID_ESTADO),
        CONSTRAINT fk_cat_persona_ciudad FOREIGN KEY (UUDI_CIUDAD)
        REFERENCES CAT_CIUDAD(UUID_CIUDAD),
        CONSTRAINT ck_persona_estado CHECK (ESTADO IN (0,99)),
        CONSTRAINT ck_persona_verificado CHECK (VERIFICADO IN (0,99))
);

COMMENT ON TABLE PERSONAS IS 'Tabla que contiene los datos personales de PERSONAS';
COMMENT ON COLUMN PERSONAS.ID_PERSONA IS 'ID de personas registradas';
COMMENT ON COLUMN PERSONAS.NOMBRE IS 'Nombre(s) de la persona registrada';
COMMENT ON COLUMN PERSONAS.APATERNO IS 'Apellido paterno';
COMMENT ON COLUMN PERSONAS.AMATERNO IS 'Apellido materno';
COMMENT ON COLUMN PERSONAS.TELEFONO IS 'Numero de telefono';
COMMENT ON COLUMN PERSONAS.CORREO IS 'Correo electrónico para login';
COMMENT ON COLUMN PERSONAS.UUDI_CIUDAD IS 'Código de la ciudad';
COMMENT ON COLUMN PERSONAS.UUDI_ESTADO IS 'Código de estado';
COMMENT ON COLUMN PERSONAS.ESTADO IS 'Bandera pra borrado logico';
COMMENT ON COLUMN PERSONAS.FECHA_ALTA IS 'Bandera pra borrado logico';
COMMENT ON COLUMN PERSONAS.VERIFICADO IS 'Bandera pra borrado logico';
COMMENT ON COLUMN PERSONAS.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN PERSONAS.CREADO_POR IS 'Usuario creador';
COMMENT ON COLUMN PERSONAS.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN PERSONAS.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN PERSONAS.NOTAS IS 'Observaciones adicionales';
COMMIT;

CREATE SEQUENCE SEQ_PERSONA_ID
    START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_INF_PERSONA_ID
    BEFORE INSERT ON PERSONAS
    FOR EACH ROW
BEGIN
    IF :NEW.ID_PERSONA IS NULL THEN
        :NEW.ID_PERSONA := 'PER-' || LPAD(SEQ_PERSONA_ID.NEXTVAL, 6, '0');
    END IF;
END;
/