alter session set current_schema = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_USUARIO_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USUARIOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE USUARIOS(
    USER_ID VARCHAR2(20) NOT NULL,
    ID_PERSONA VARCHAR2(20) NOT NULL,
    PASSWORD VARCHAR(60),
    ID_ROL VARCHAR2(20) NOT NULL,
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_ALTA  DATE DEFAULT SYSDATE,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT pk_usuario PRIMARY KEY (USER_ID),
    CONSTRAINT fk_usuario_persona
        FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA),
    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (ID_ROL) REFERENCES CAT_ROL(ID_ROL),
    CONSTRAINT ck_usuario_estado CHECK (ESTADO IN ('0','99'))
);

COMMENT ON TABLE USUARIOS IS 'Tabla que contiene los datos de acceso';
COMMENT ON COLUMN USUARIOS.USER_ID IS 'ID único del usuario';
COMMENT ON COLUMN USUARIOS.ID_PERSONA IS 'Referencia a la persona';
COMMENT ON COLUMN USUARIOS.PASSWORD IS 'contraseña encriptada';
COMMENT ON COLUMN USUARIOS.ID_ROL IS 'Clave del rol';
COMMENT ON COLUMN USUARIOS.ESTADO IS '0=Activo | 99=Inactivo';
COMMENT ON COLUMN USUARIOS.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN USUARIOS.CREADO_POR IS 'Usuario creador';
COMMENT ON COLUMN USUARIOS.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN USUARIOS.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN USUARIOS.NOTAS IS 'Observaciones adicionales';
COMMENT ON COLUMN USUARIOS.FECHA_ALTA IS 'Fecha de alta del usuario despues de la verificacion de correo';
COMMIT;

CREATE SEQUENCE SEQ_USUARIO_ID
    START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_USUARIO_ID
    BEFORE INSERT ON USUARIOS
    FOR EACH ROW
BEGIN
    IF :NEW.USER_ID IS NULL THEN
        :NEW.USER_ID := 'USER-' || LPAD(SEQ_USUARIO_ID.NEXTVAL, 6, '0');
    END IF;
END;
/