alter session set current_schema = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TELEFONO_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TELEFONOS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE TELEFONOS(
     ID_TELEFONO VARCHAR2(36) NOT NULL,
     ID_CLIENTE VARCHAR2(36) NOT NULL,
     TELEFONO VARCHAR2(15) NOT NULL,
     ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
     FECHA_ALTA  DATE DEFAULT SYSDATE,
     FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
     CREADO_POR VARCHAR2(36) NOT NULL,
     FECHA_ACTUALIZACION TIMESTAMP,
     ACTUALIZADO_POR VARCHAR2(36),
     NOTAS VARCHAR2(100),
     CONSTRAINT pk_id_telefono_telefonos PRIMARY KEY (ID_TELEFONO),
     CONSTRAINT fk_id_cliente_telefonos
         FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

COMMENT ON TABLE TELEFONOS IS 'Tabla que contiene los telefonos de los clientes';
COMMENT ON COLUMN TELEFONOS.ID_TELEFONO IS 'Llave primaria de la tabla TELEFONOS';
COMMENT ON COLUMN TELEFONOS.ID_CLIENTE IS 'Llave foranea ID_CLIENTE que hace referencia a la tabla CLIENTES';
COMMENT ON COLUMN TELEFONOS.TELEFONO IS 'Número teléfonico del Cliente';
COMMENT ON COLUMN TELEFONOS.ESTADO IS 'Bandera para borrado logico';
COMMENT ON COLUMN TELEFONOS.FECHA_ALTA IS 'Campo de control que indica la Fecha de Alta en la BD';
COMMENT ON COLUMN TELEFONOS.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN TELEFONOS.CREADO_POR IS 'Usuario creador';
COMMENT ON COLUMN TELEFONOS.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN TELEFONOS.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN TELEFONOS.NOTAS IS 'Observaciones adicionales';
COMMIT;

CREATE SEQUENCE SEQ_TELEFONO_ID
    START WITH 1 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER SEQ_TELEFONO_ID
    BEFORE INSERT ON TELEFONOS
    FOR EACH ROW
BEGIN
    IF :NEW.ID_TELEFONO IS NULL THEN
        :NEW.ID_TELEFONO := 'TEL-' || LPAD(SEQ_TELEFONO_ID.NEXTVAL, 6, '0');
    END IF;
END;
/