alter session set current_schema = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TOKEN_VERIFICACION';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE TOKEN_VERIFICACION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE TOKEN_VERIFICACION(
    ID_TOKEN_VERIFICACION VARCHAR2(20) NOT NULL,
    ID_PERSONA VARCHAR2(36) NOT NULL,
    TOKEN VARCHAR2(255) NOT NULL,
    ID_TIPO_TOKEN VARCHAR2(20) NOT NULL,
    USADO NUMBER(1) DEFAULT 0 NOT NULL,
    CADUCADO NUMBER(1) DEFAULT 0 NOT NULL,
    FECHA_ALTA TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_EXPIRACION TIMESTAMP NOT NULL,
    FECHA_USO TIMESTAMP,
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    NOTAS VARCHAR2(100),
    CONSTRAINT pk_id_token_verificacion PRIMARY KEY (ID_TOKEN_VERIFICACION),
    CONSTRAINT fk_tokenv_usuario
      FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA),
    CONSTRAINT fk_tipo_tokenv
        FOREIGN KEY (ID_TIPO_TOKEN) REFERENCES CAT_TIPO_TOKEN(ID_TIPO_TOKEN),
    CONSTRAINT uk_token UNIQUE(TOKEN),
    CONSTRAINT ck_token_usado CHECK(USADO IN (0,1)),
    CONSTRAINT ck_token_caducado CHECK(USADO IN (0,1))
);

COMMENT ON TABLE TOKEN_VERIFICACION IS 'Tabla que contiene los Tokens de verificación';
COMMENT ON COLUMN TOKEN_VERIFICACION.ID_TOKEN_VERIFICACION IS 'Llave primaria de la tabla TOKEN VERIFICACION';
COMMENT ON COLUMN TOKEN_VERIFICACION.ID_PERSONA IS 'Clave de la persona';
COMMENT ON COLUMN TOKEN_VERIFICACION.TOKEN IS 'Token de verificacion';
COMMENT ON COLUMN TOKEN_VERIFICACION.ID_TIPO_TOKEN IS 'ID tipo de token';
COMMENT ON COLUMN TOKEN_VERIFICACION.USADO IS 'Indica si el token ya fue usado';
COMMENT ON COLUMN TOKEN_VERIFICACION.CADUCADO IS 'Indica si el token ya ha caducado';
COMMENT ON COLUMN TOKEN_VERIFICACION.FECHA_ALTA IS 'Fecha de creación del token';
COMMENT ON COLUMN TOKEN_VERIFICACION.FECHA_EXPIRACION IS 'Fecha de expiración del token';
COMMENT ON COLUMN TOKEN_VERIFICACION.FECHA_USO IS 'Fecha de uso del token';
COMMENT ON COLUMN TOKEN_VERIFICACION.ESTADO IS 'Bandera para borrado logico';
COMMENT ON COLUMN TOKEN_VERIFICACION.NOTAS IS 'Observaciones adicionales';
COMMIT;

CREATE SEQUENCE SEQ_TOKEN_VERIFICACION
    START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER SEQ_TOKEN_VERIFICACION
    BEFORE INSERT ON TOKEN_VERIFICACION
    FOR EACH ROW
BEGIN
    IF :NEW.ID_TOKEN_VERIFICACION IS NULL THEN
        :NEW.ID_TOKEN_VERIFICACION := 'TKV-' || LPAD(SEQ_TOKEN_VERIFICACION.NEXTVAL, 9, '0');
    END IF;
END;
/