alter session set current_schema = SECURITY;

BEGIN
    EXECUTE IMMEDIATE  'DROP TABLE CAT_ESTADO_FACTURA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE  'DROP SEQUENCE SEQ_ESTADO_FACTURA';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CAT_ESTADO_FACTURA(
    ID_ESTADO_FACTURA VARCHAR2(15) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(100),
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_ESTADO_FACTURA PRIMARY KEY (ID_ESTADO_FACTURA),
    CONSTRAINT CK_ESTADO_FACTURA CHECK (ESTADO IN (0, 99))
);

COMMENT ON TABLE CAT_ESTADO_FACTURA IS 'Tabla catálogo de tipo de estado factura';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.ID_ESTADO_FACTURA IS 'Clave del estado de la factura';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.NOMBRE IS 'Nombre del estado de la factura';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.DESCRIPTION IS 'Descripción del estado de la factura';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.ESTADO IS '0 = Activo | 99 = Inactivo';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.FECHA_CREACION is 'Fecha de creación';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.CREADO_POR is 'Usuario creador';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.FECHA_ACTUALIZACION is 'Fecha de actualización';
COMMENT ON COLUMN CAT_ESTADO_FACTURA.ACTUALIZADO_POR is 'Usuario que actualizó';

CREATE SEQUENCE SEQ_ESTADO_FACTURA START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_ID_ESTADO_FACTURA_ID
BEFORE INSERT ON CAT_ESTADO_FACTURA
FOR EACH ROW
BEGIN
    IF :NEW.ID_ESTADO_FACTURA IS NULL THEN
        :NEW.ID_ESTADO_FACTURA := 'EFAC' || LPAD(SEQ_ESTADO_FACTURA.NEXTVAL, 3, '0');
    END IF;
END;
/

/*
    INSERTS
 */

INSERT INTO CAT_ESTADO_FACTURA(NOMBRE, DESCRIPTION, CREADO_POR)
VALUES ('PAGADA', 'Factura Pagada', '57e8cc9c-9dB3-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_ESTADO_FACTURA(NOMBRE, DESCRIPTION, CREADO_POR)
VALUES ('CANCELADA', 'Factura Cancelada', '57e8cc9c-9dB3-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_ESTADO_FACTURA(NOMBRE, DESCRIPTION, CREADO_POR)
VALUES ('EN PROCESO', 'Factura en Proceso de pago', '57e8cc9c-9dB3-4e76-99c1-d6de3d7a984e');

COMMIT;

SELECT * FROM CAT_ESTADO_FACTURA;