alter session set current_schema = SECURITY;

BEGIN
    EXECUTE IMMEDIATE  'DROP TABLE CAT_ESTADO_PAGO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE  'DROP SEQUENCE SEQ_ESTADO_PAGO';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CAT_ESTADO_PAGO(
       ID_ESTADO_PAGO VARCHAR2(15) NOT NULL,
       NOMBRE VARCHAR2(50) NOT NULL,
       DESCRIPTION VARCHAR2(100),
       ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
       FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
       CREADO_POR VARCHAR2(36) NOT NULL,
       FECHA_ACTUALIZACION TIMESTAMP,
       ACTUALIZADO_POR VARCHAR2(36),
       NOTAS VARCHAR2(100),
       CONSTRAINT PK_ESTADO_PAGO PRIMARY KEY (ID_ESTADO_PAGO),
       CONSTRAINT CK_ESTADO_PAGO CHECK (ESTADO IN (0, 99))
);

COMMENT ON TABLE CAT_ESTADO_PAGO IS 'Tabla catálogo de tipo de estado pago';
COMMENT ON COLUMN CAT_ESTADO_PAGO.ID_ESTADO_PAGO IS 'Clave del estado de la pago';
COMMENT ON COLUMN CAT_ESTADO_PAGO.NOMBRE IS 'Nombre del estado de la pago';
COMMENT ON COLUMN CAT_ESTADO_PAGO.DESCRIPTION IS 'Descripción del estado de la pago';
COMMENT ON COLUMN CAT_ESTADO_PAGO.ESTADO IS '0 = Activo | 99 = Inactivo';
COMMENT ON COLUMN CAT_ESTADO_PAGO.FECHA_CREACION is 'Fecha de creación';
COMMENT ON COLUMN CAT_ESTADO_PAGO.CREADO_POR is 'Usuario creador';
COMMENT ON COLUMN CAT_ESTADO_PAGO.FECHA_ACTUALIZACION is 'Fecha de actualización';
COMMENT ON COLUMN CAT_ESTADO_PAGO.ACTUALIZADO_POR is 'Usuario que actualizó';
COMMENT ON COLUMN CAT_ESTADO_PAGO.NOTAS is 'Observaciones adicionales';

CREATE SEQUENCE SEQ_ESTADO_PAGO START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_ID_ESTADO_PAGO_ID
    BEFORE INSERT ON CAT_ESTADO_PAGO
    FOR EACH ROW
BEGIN
    IF :NEW.ID_ESTADO_PAGO IS NULL THEN
        :NEW.ID_ESTADO_PAGO := 'EFAC' || LPAD(SEQ_ESTADO_PAGO.NEXTVAL, 3, '0');
    END IF;
END;
/

/*
    INSERTS
 */

INSERT INTO CAT_ESTADO_PAGO(NOMBRE, DESCRIPTION, CREADO_POR)
VALUES ('PROCESADO', 'pago PROCESADO CON EXITO', '57e8cc9c-9dB3-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_ESTADO_PAGO(NOMBRE, DESCRIPTION, CREADO_POR)
VALUES ('CANCELADO', 'pago CANCELADO por el cliente', '57e8cc9c-9dB3-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_ESTADO_PAGO(NOMBRE, DESCRIPTION, CREADO_POR)
VALUES ('EN PROCESO', 'pago EN PROCESO de pago', '57e8cc9c-9dB3-4e76-99c1-d6de3d7a984e');

COMMIT;

SELECT * FROM CAT_ESTADO_PAGO;