alter session set current_schema = SECURITY;

BEGIN
    EXECUTE IMMEDIATE  'DROP TABLE CAT_ROL CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE  'DROP SEQUENCE SEQ_ROL';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CAT_ROL(
        ID_ROL VARCHAR2(10) NOT NULL,
        NOMBRE_ROL VARCHAR2(50) NOT NULL,
        DESCRIPTION VARCHAR2(100),
        ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
        FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        CREADO_POR VARCHAR2(36) NOT NULL,
        FECHA_ACTUALIZACION TIMESTAMP,
        ACTUALIZADO_POR VARCHAR2(36),
        NOTAS VARCHAR2(100),
        CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL),
        CONSTRAINT CK_ROL_ESTADO CHECK (ESTADO IN (0, 99))
);

COMMENT ON TABLE CAT_ROL IS 'Tabla catálogo de ROLES';
COMMENT ON COLUMN CAT_ROL.ID_ROL IS 'Clave del ROL ejemplo RL-001';
COMMENT ON COLUMN CAT_ROL.NOMBRE_ROL IS 'Nombre del ROL';
COMMENT ON COLUMN CAT_ROL.DESCRIPTION IS 'Descripción del ROL';
COMMENT ON COLUMN CAT_ROL.ESTADO IS '0 = Activo | 99 = Inactivo';
COMMENT ON COLUMN CAT_ROL.FECHA_CREACION is 'Fecha de creación';
COMMENT ON COLUMN CAT_ROL.CREADO_POR is 'Usuario creador';
COMMENT ON COLUMN CAT_ROL.FECHA_ACTUALIZACION is 'Fecha de actualización';
COMMENT ON COLUMN CAT_ROL.ACTUALIZADO_POR is 'Usuario que actualizó';
COMMENT ON COLUMN CAT_ROL.NOTAS is 'Observaciones adicionales';

CREATE SEQUENCE SEQ_ROL START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_ROL_ID
    BEFORE INSERT ON CAT_ROL
    FOR EACH ROW
BEGIN
    IF :NEW.ID_ROL IS NULL THEN
        :NEW.ID_ROL := 'RL-' || LPAD(SEQ_ROL.NEXTVAL, 3, '0');
    END IF;
END;
/

/*
    INSERTS
 */

INSERT INTO CAT_ROL(NOMBRE_ROL, DESCRIPTION, CREADO_POR)
VALUES ('ADMIN', 'Admin Sistema', '57e8cc9c-9dB3-4e76-99c1-d6de3d7a984e');

INSERT INTO CAT_ROL(NOMBRE_ROL, DESCRIPTION, CREADO_POR)
VALUES ('USER', 'Usuario estandar', '57e8cc9c-9dB3-4e76-99c1-d6de3d7a984e');

COMMIT;

SELECT * FROM CAT_ROL;