alter session set current_schema = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CAT_STATUS_MENSAJE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_STATUS_MENSAJE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CAT_STATUS_MENSAJE(
    ID_STATUS_MENSAJE VARCHAR2(15) NOT NULL,
    NOMBRE_STATUS VARCHAR2(40) NOT NULL,
    DESCRIPTION VARCHAR2(100),
    ESTADO NUMBER(2) DEFAULT 1 NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT pk_id_cat_status_menssage PRIMARY KEY (ID_STATUS_MENSAJE)
);

COMMENT ON TABLE CAT_STATUS_MENSAJE IS 'Tabla que contiene los estados de los mensajes de contacto';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.ID_STATUS_MENSAJE IS 'ID de estado';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.NOMBRE_STATUS IS 'Estado del mensaje';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.DESCRIPTION IS 'Descripción del estado';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.ESTADO IS 'Estado del registro';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.CREADO_POR IS 'Usuario Creador';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN CAT_STATUS_MENSAJE.NOTAS IS 'Observaciones adicionales';
COMMIT;

CREATE SEQUENCE SEQ_STATUS_MENSAJE START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_STATUS_MENSAJE_ID
BEFORE INSERT ON CAT_STATUS_MENSAJE
FOR EACH ROW
BEGIN
    IF :NEW.ID_STATUS_MENSAJE IS NULL THEN
        :NEW.ID_STATUS_MENSAJE := 'CSM-' || LPAD(SEQ_STATUS_MENSAJE.NEXTVAL, 3, '0');
    END IF;
END;