alter session set current_schema = SECURITY;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CAT_TIPO_CLIENTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_TIPO_CLIENTE_ID';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE CAT_TIPO_CLIENTE(
    ID_TIPO_CLIENTE VARCHAR2(15) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(100),
    ESTADO NUMBER(2) DEFAULT 0 NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREADO_POR VARCHAR2(36) NOT NULL,
    FECHA_ACTUALIZACION TIMESTAMP,
    ACTUALIZADO_POR VARCHAR2(36),
    NOTAS VARCHAR2(100),
    CONSTRAINT PK_TIPO_CLIENTE PRIMARY KEY (ID_TIPO_CLIENTE),
    CONSTRAINT CK_TIPO_CLIENTE CHECK (ESTADO IN (0, 99))
);

COMMENT ON TABLE CAT_TIPO_CLIENTE IS 'Tabla que contiene los estados de los TIPOS DE CLIENTES';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.ID_TIPO_CLIENTE IS 'ID del TIPO DEL CLIENTE';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.NOMBRE IS 'Nombre del tipo de cliente';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.DESCRIPTION IS 'Descripción del tipo de cliente';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.ESTADO IS 'Estado del registro';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.FECHA_CREACION IS 'Fecha de creación';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.CREADO_POR IS 'Usuario Creador';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.FECHA_ACTUALIZACION IS 'Fecha de actualización';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.ACTUALIZADO_POR IS 'Usuario que actualizó';
COMMENT ON COLUMN CAT_TIPO_CLIENTE.NOTAS IS 'Observaciones adicionales';
COMMIT;

CREATE SEQUENCE SEQ_TIPO_CLIENTE_ID START WITH 0 INCREMENT BY 1 MINVALUE 0 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_TIPO_CLIENTE_ID
    BEFORE INSERT ON CAT_TIPO_CLIENTE
    FOR EACH ROW
BEGIN
    IF :NEW.ID_TIPO_CLIENTE IS NULL THEN
        :NEW.ID_TIPO_CLIENTE := 'TCLI' || LPAD(SEQ_TIPO_CLIENTE_ID.NEXTVAL, 3, '0');
    END IF;
END;